### ISSUE TITLE
Auto-wear armor

### ISSUE THREAD

**Issue by jogurtman** [cervinakuy/KitPvP#309]
Hello, 
thank you for this nice plugin. 
I would like to know if it is possible to automatically wear the items in `Inventory: Armor:` (config). Currently, these items are added to the hotbar and the player has to manually put them on. It would be great if the armor-items are directly in the armor-slots of the player. Is there any config setting I couldn't find?
Thanks in advance.

**Comment by cervinakuy** [comment]
Armor should automatically be equipped, assuming you are wearing the armor when executing /kp create. Are you wearing the armor when running /kp create?

**Comment by jogurtman** [comment]
Kinda good news: Another plugin I use had the same problem with armor slots. It seems that Paper is causing the issue, but fortunately it can be fixed.
This may help (same issue): https://github.com/RockinChaos/ItemJoin/issues/625

**Comment by realcondar** [comment]
Is the fix on the authors end or on papers end?

**Comment by jogurtman** [comment]
> Is the fix on the authors end or on papers end?

Well, just have a look at it. It is on the author's end. However, I don't know if paper changed something related to this since then (probably not).

**Comment by LowIQWithAutism** [comment]
@cervinakuy Will this be fixed???????????? this is a massive problem why are you forcing us to suffer

**Comment by cervinakuy** [comment]
I believe this was fixed on newer versions of Paper Spigot?

**Comment by BeekrBonkr** [comment]
This is still an issue on a newer versions, are there any plans to fix?
